# Generated by Django 4.1.4 on 2023-01-14 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('autor', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('titulo', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('universo', models.CharField(blank=True, max_length=40, null=True)),
                ('Primer_cuerpo', models.TextField(blank=True, max_length=10000000000, null=True)),
                ('Segundo_cuerpo', models.TextField(blank=True, max_length=10000000000, null=True)),
                ('Primer_imagen', models.ImageField(blank=True, upload_to='posts')),
                ('Segunda_imagen', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('usuario_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
