# Generated by Django 4.1.4 on 2023-01-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_posteo_delete_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posteo',
            old_name='Primer_cuerpo',
            new_name='cuerpo',
        ),
        migrations.RenameField(
            model_name='posteo',
            old_name='Primer_imagen',
            new_name='imagen',
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='Segunda_imagen',
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='Segundo_cuerpo',
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='usuario_post',
        ),
    ]
