# Generated by Django 4.1.3 on 2023-01-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_rename_primer_cuerpo_posteo_cuerpo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='email',
        ),
        migrations.AddField(
            model_name='posteo',
            name='username',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='universo',
            field=models.CharField(blank=True, choices=[('LotR', 'Lord of the Rings'), ('Narnia', 'Narnia'), ('Mistborn', 'Mistborn'), ('GoT', 'Game of Thrones'), ('Otros', 'Otros')], max_length=40, null=True),
        ),
    ]
