# Generated by Django 4.1.4 on 2023-01-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_remove_posteo_email_posteo_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(blank=True, default='posts/default.jpeg', upload_to='posts'),
        ),
    ]
