# Generated by Django 4.1.3 on 2023-01-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0002_perfil_avatar_perfil_bio_perfil_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, default='avatares/default.jpg', upload_to='avatares/'),
        ),
    ]
