# Generated by Django 4.1.3 on 2023-01-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0004_alter_perfil_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='alias',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
