# Generated by Django 4.1.4 on 2023-01-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0008_remove_canal_texto_remove_canal_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='paginaweb',
            field=models.URLField(blank=True),
        ),
    ]
